In [1]:
!dir

 Volume in drive C is Acer
 Volume Serial Number is D812-1956

 Directory of C:\Code Playground\Palmprintdetection_project

14-04-2023  16:52    <DIR>          .
04-04-2023  21:06    <DIR>          ..
05-02-2023  14:48    <DIR>          .ipynb_checkpoints
02-02-2023  17:09                23 .jovianrc
14-11-2022  01:49           655,831 9939-Article Text-17682-1-10-20210714.pdf
23-01-2023  20:33    <DIR>          dataset
14-04-2023  16:49            51,775 PalmPrint Detection model optimized data.ipynb
27-01-2023  20:10            43,311 PalmPrint Detection model.ipynb
25-01-2023  00:01    <DIR>          Palmprint_detection_guass.model
05-02-2023  16:09    <DIR>          Palmprint_detection_guass_optimzed.model
24-01-2023  23:49    <DIR>          Palmprint_detection_meanth.model
05-02-2023  15:57    <DIR>          Palmprint_detection_meanth_optimized.model
14-04-2023  16:52         2,316,194 Preprocessing_dataset.ipynb
27-01-2023  19:52         3,016,443 test_img.jpg
14-04-2023  16:49  

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import os
import cv2 as cv
import re 
from collections import Counter
import tensorflow as tf
from tensorflow.keras.layers import Dense,Activation,Flatten,Conv2D,MaxPooling2D
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
#Meanth data
pickle_in=open("X_MeanThresholding.pickle","rb")
X_meanth=pickle.load(pickle_in)
pickle_in.close()
pickle_in=open("y_MeanThresholding.pickle","rb")
y_meanth=pickle.load(pickle_in)
pickle_in.close()

In [5]:
X_meanth.shape

(2166, 220, 270, 1)

In [6]:
y_meanth.shape

(2166,)

In [7]:
len(X_meanth)

2166

In [8]:
len(y_meanth)

2166

In [9]:
Xmtrain,Xmtest,ymtrain,ymtest=train_test_split(X_meanth,y_meanth,test_size=0.2,random_state=42)

In [10]:
print(len(Xmtrain),len(Xmtest),len(ymtrain),len(ymtest))

1732 434 1732 434


In [11]:
type(Xmtrain)
type(ymtrain)
ymtrain.dtype

dtype('int32')

In [12]:
from keras.optimizers import Adam

model = Sequential()

# Add the first layer (convolutional layer)
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', activation='relu',input_shape=Xmtrain.shape[1:]))

# Add the second layer (max pooling layer)
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))

# Add the third layer (convolutional layer)
model.add(Conv2D(filters=64, kernel_size=(3,3), padding='same', activation='relu',input_shape=Xmtrain.shape[1:]))

# Add the forth layer (max pooling layer)
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))

# Add the fifth layer (flatten layer)
model.add(Flatten())

# Add the output layer
model.add(Dense(12, activation='softmax'))

# Compile the model
# optimizer = Adam(learning_rate=0.00001)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# model.fit(Xmtrain,ymtrain,epochs=4,validation_split=0.1)

In [13]:
model.fit(Xmtrain,ymtrain,epochs=4,validation_split=0.1)

Epoch 1/4
49/49 [==============================] - 40s 803ms/step - loss: 449.0456 - accuracy: 0.2606 - val_loss: 1.5445 - val_accuracy: 0.5345
Epoch 2/4
49/49 [==============================] - 41s 835ms/step - loss: 0.3328 - accuracy: 0.9166 - val_loss: 0.8223 - val_accuracy: 0.7874
Epoch 3/4
49/49 [==============================] - 39s 792ms/step - loss: 0.0352 - accuracy: 0.9936 - val_loss: 0.8092 - val_accuracy: 0.7989
Epoch 4/4
49/49 [==============================] - 36s 735ms/step - loss: 0.0156 - accuracy: 0.9987 - val_loss: 0.9746 - val_accuracy: 0.7874


In [ ]:
np.array(list(map(np.argmax,model.predict(Xmtest))))

In [13]:
ymtest

array([ 9,  5,  4,  9,  8, 10,  2,  0,  5,  2,  7,  3,  9, 10,  2, 10,  2,
        5,  0,  3,  8,  6,  3,  5, 10,  1,  8,  9,  6,  2,  7,  6,  3,  0,
        8,  2,  9, 10, 11,  1,  6, 10,  6,  3,  2,  1, 11, 10,  7,  8,  6,
        7,  3,  9,  3,  6,  9,  9,  3, 11,  0,  0,  4,  5,  3,  0,  0,  0,
       10,  6,  9,  3,  0,  3,  4,  9,  9,  4, 10,  0,  9, 11,  7, 11,  7,
        7, 11,  1,  2,  2,  6,  0,  3,  6, 10,  7,  1,  3,  2,  9,  4,  1,
        8,  6, 10,  0,  6, 10,  5,  5,  5,  9,  9,  0,  8,  0,  1, 10,  8,
        4,  4,  1,  9, 11,  3,  7, 10,  4,  2, 10, 11,  4,  6,  9,  2,  6,
        9,  5,  0, 11, 11,  2,  3,  1,  0,  9,  9, 10,  9,  1,  2,  7,  1,
        6,  7, 11, 11,  3,  4,  2, 10, 10,  6,  3, 11,  0,  2,  4,  9,  0,
        4,  7,  0,  3,  6,  3,  9, 11,  2,  2,  3,  5,  7,  2,  0,  3,  6,
        4,  4,  1,  1,  7,  3,  0, 10,  7,  6,  1,  0,  6,  7,  3,  5,  4,
        4,  3,  6,  2,  7,  7,  9,  5, 10,  6,  8,  6,  2,  2,  2,  9, 11,
        1,  9,  1,  9, 10

In [83]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 220, 270, 32)      320       
                                                                 
 max_pooling2d_12 (MaxPoolin  (None, 110, 135, 32)     0         
 g2D)                                                            
                                                                 
 conv2d_13 (Conv2D)          (None, 110, 135, 64)      18496     
                                                                 
 max_pooling2d_13 (MaxPoolin  (None, 55, 67, 64)       0         
 g2D)                                                            
                                                                 
 flatten_6 (Flatten)         (None, 235840)            0         
                                                                 
 dense_6 (Dense)             (None, 12)               

In [21]:
# from sklearn.metrics import r2_score
# r2_score(ymtest,model.predict(Xmtest))
len(Xmtest)

434

In [22]:
len(ymtest)

434

In [84]:
model.save("Palmprint_detection_meanth_optimized.model")

INFO:tensorflow:Assets written to: Palmprint_detection_meanth_optimized.model\assets


INFO:tensorflow:Assets written to: Palmprint_detection_meanth_optimized.model\assets


In [24]:
pickle_in=open("X_GuassThresholding.pickle","rb")
X_guass=pickle.load(pickle_in)
pickle_in.close()
pickle_in=open("y_GuassThresholding.pickle","rb")
y_guass=pickle.load(pickle_in)
pickle_in.close()

In [25]:
X_guass.shape

(2166, 220, 270, 1)

In [26]:
y_guass.shape

(2166,)

In [27]:
X_guass

array([[[[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[  0],
         [  0],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[  0],
         [  0],
         [  0],
         ...,
         [255],
         [255],
         [255]],

        ...,

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[255],
         [255],
         [255],
         ...,
         [  0],
         [  0],
         [  0]],

        [[255],
         [255],
         [255],
         ...,
         [  0],
         [  0],
         [  0]]],


       [[[  0],
         [  0],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[  0],
         [  0],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[  0],
         [  0],
         [255],
         ...,
         [255],
         [

In [28]:
y_guass

array([ 8,  7, 11, ...,  6,  4,  3])

In [29]:
Xgtrain,Xgtest,ygtrain,ygtest=train_test_split(X_guass,y_guass,test_size=0.2,random_state=42)

In [30]:
print(len(Xgtrain),len(Xgtest),len(ygtrain),len(ygtest))

1732 434 1732 434


In [90]:
from keras.optimizers import Adam

modelGuass = Sequential()

# Add the first layer (convolutional layer)
modelGuass.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', activation='relu',input_shape=Xgtrain.shape[1:]))

# Add the second layer (max pooling layer)
modelGuass.add(MaxPooling2D(pool_size=(2, 2), strides=2))

# Add the third layer (convolutional layer)
modelGuass.add(Conv2D(filters=64, kernel_size=(3,3), padding='same', activation='relu',input_shape=Xgtrain.shape[1:]))

# Add the forth layer (max pooling layer)
modelGuass.add(MaxPooling2D(pool_size=(2, 2), strides=2))

# Add the fifth layer (flatten layer)
modelGuass.add(Flatten())

# Add the output layer
modelGuass.add(Dense(12, activation='softmax'))

# Compile the model
# optimizer = Adam(learning_rate=0.00001)
modelGuass.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


modelGuass.fit(Xgtrain,ygtrain,epochs=3,validation_split=0.1)

Epoch 1/3
49/49 [==============================] - 44s 878ms/step - loss: 587.7504 - accuracy: 0.1502 - val_loss: 2.3118 - val_accuracy: 0.2471
Epoch 2/3
49/49 [==============================] - 41s 843ms/step - loss: 0.8205 - accuracy: 0.7606 - val_loss: 1.0117 - val_accuracy: 0.7529
Epoch 3/3
49/49 [==============================] - 42s 861ms/step - loss: 0.0546 - accuracy: 0.9884 - val_loss: 0.7663 - val_accuracy: 0.8046


In [91]:
np.array(list(map(np.argmax,modelGuass.predict(Xgtest)))).reshape(-1)

14/14 [==============================] - 3s 210ms/step


array([ 3, 11,  8,  3,  7,  5,  5,  1,  1,  0,  7,  0,  5, 10,  2,  9,  2,
       10,  8, 11,  0,  2,  9,  1,  2,  7, 11, 11,  7,  7,  2,  1,  6,  9,
        4,  2,  8,  5,  3,  5,  1,  8,  0,  7, 10,  8,  3,  7,  2,  6,  4,
       10,  6,  5, 11,  8,  2,  3,  3,  0,  9,  2,  8,  3, 11,  3,  8,  7,
        6,  1,  1,  8,  7,  2,  4,  2,  0,  3,  2,  2,  9, 10,  6,  2,  5,
        2, 11,  1,  0,  2, 10,  3, 11,  9,  7, 11, 11,  2,  0,  6,  8,  0,
       10,  5,  2,  4, 11,  6,  4, 10,  8,  0,  9,  5, 11,  7,  5,  4,  1,
        9,  4,  2,  8,  8, 11,  4, 10,  1,  8,  3,  8,  2,  2,  9,  0,  0,
        7,  1,  0,  3,  3,  8,  2, 10,  6,  1,  4,  9,  5, 10,  1,  0,  6,
        9,  2,  7, 11,  9,  1,  7,  8, 11,  2,  4,  5,  9,  3,  8,  1,  4,
       11,  3,  1, 11,  7,  0,  6,  3,  6,  2,  1,  1,  1,  6,  2,  4,  2,
        3, 11,  1,  1, 10, 11,  2,  1,  3,  1,  7,  9, 11,  2,  9,  1,  7,
        6,  9,  8,  7,  7,  2,  3,  3, 10,  0, 11,  6,  6,  0,  6,  5,  2,
        8,  7,  3,  1,  5

In [36]:
ygtest

array([11, 11,  8,  1,  7,  5,  5,  1,  1,  2,  7,  0,  5,  9,  2,  9,  2,
        6,  8, 11,  0,  3,  9,  1,  2,  7, 11, 11,  7,  7,  5,  1,  6,  9,
        4,  2,  8,  0,  3,  5,  4,  0,  2,  8, 10,  8,  3,  7,  2,  6,  4,
       10,  6, 10, 11,  0,  2,  3,  3,  0,  9,  2,  8,  3, 11,  3,  8,  5,
        6,  6,  1,  8,  7,  2,  4,  2,  0,  0,  5,  2,  9, 10,  5,  2,  4,
        2, 11,  1,  0,  2,  7,  3, 11,  9,  3,  7, 11,  2,  1,  6,  8,  0,
       10,  5,  2,  4, 11,  6,  4, 10,  8,  0,  9,  7, 11,  7,  5,  4,  1,
        9,  4,  5,  8,  9, 11,  4, 10,  1,  8,  4,  8, 10,  2,  9,  0,  0,
        7,  1,  0,  3,  3,  8,  2, 11,  6,  1,  4,  9,  5, 10,  1,  0,  4,
        9,  2,  7, 11,  6,  1,  7,  8, 11,  2,  4, 10, 10,  3,  8,  6,  4,
       11,  3,  1, 11,  5,  0,  6,  3,  6,  2,  1,  1,  1,  1,  2,  4,  8,
        3, 11,  8,  1,  1, 11,  2,  1,  3,  8,  7,  0, 11,  2,  9,  6,  7,
        4,  9,  8,  7,  7,  2,  3,  3, 10,  5,  6,  6,  6,  0,  6,  5,  2,
        8, 11,  3,  1,  5

In [67]:
modelGuass.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_32 (Conv2D)          (None, 200, 200, 32)      320       
                                                                 
 max_pooling2d_32 (MaxPoolin  (None, 100, 100, 32)     0         
 g2D)                                                            
                                                                 
 conv2d_33 (Conv2D)          (None, 100, 100, 64)      18496     
                                                                 
 max_pooling2d_33 (MaxPoolin  (None, 50, 50, 64)       0         
 g2D)                                                            
                                                                 
 flatten_16 (Flatten)        (None, 160000)            0         
                                                                 
 dense_16 (Dense)            (None, 12)              

In [92]:
modelGuass.save("Palmprint_detection_guass_optimzed.model")

INFO:tensorflow:Assets written to: Palmprint_detection_guass_optimzed.model\assets


INFO:tensorflow:Assets written to: Palmprint_detection_guass_optimzed.model\assets


In [86]:
def UploadImgMeanth(PATH):
    wavelength = 10
    orientation = 0
    phase_offset = 1*np.pi
    sigma = 4.2
    IMGSIZE=500
    grayimg=cv.imread(os.path.join(PATH),cv.IMREAD_GRAYSCALE)
    resizedimg=cv.resize(grayimg,(IMG_SIZE,IMG_SIZE))
    croppedimg=resizedimg[250:470,100:370]
    gaborimg=[]
    gaborimg.append(gabor_filter(croppedimg,10,0,1*np.pi,4.2))
    gaborimg.append(gabor_filter(croppedimg,10,0,0,3.9))
    gaborimg.append(gabor_filter(croppedimg,10,0,1*np.pi,4.3))
    gaborimg.append(gabor_filter(croppedimg,10,30,1*np.pi,4.3))
    gaborimg.append(gabor_filter(croppedimg,10,30,1*np.pi,4.2))
    gaborimg.append(gabor_filter(croppedimg,10,25,0,3.9))
    medianimg=map(medianblurFunc,gaborimg)
    meanthimg=list(map(Mean_thresholding,medianimg))
#     L=[meanthinmg]
#     return np.array(L).reshape(-1,220,270,1)
    return np.array(meanthimg).reshape(-1,220,270,1)

In [14]:
new_model=tf.keras.models.load_model("Palmprint_detection_meanth_optimized.model")

In [87]:
img=UploadImgMeanth("test_img.jpg")


In [88]:
# plt.imshow(img)
img

array([[[[255],
         [255],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[255],
         [255],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[255],
         [255],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        ...,

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]]],


       [[[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [

In [89]:
list(map(np.argmax,model.predict(img)))

1/1 [==============================] - 0s 72ms/step


[3, 8, 5, 10, 11, 10]

In [39]:
def gabor_filter(img, wavelength, orientation, phase_offset, sigma):
    # Create the filter kernel
    kernel = cv.getGaborKernel((15,15), sigma, orientation, wavelength, 0.5, phase_offset)
    # Convolve the image with the filter
    filtered_img = cv.filter2D(img, cv.CV_8UC3, kernel)
    # Normalize the output image
#     return cv.normalize(filtered_img, None, 0, 255, cv.NORM_MINMAX)
    return filtered_img

In [40]:
def medianblurFunc(img):
    return cv.medianBlur(img,3)

In [41]:
def Mean_thresholding(img):
    meanth=cv.adaptiveThreshold(img,255,cv.ADAPTIVE_THRESH_MEAN_C,cv.THRESH_BINARY,11,2)
    return meanth

In [42]:
def Gaussian_thresholding(img):
    return cv.adaptiveThreshold(img,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,cv.THRESH_BINARY,11,2)

In [94]:
def UploadImgGuass(PATH):
    wavelength = 10
    orientation = 0
    phase_offset = 1*np.pi
    sigma = 4.2
    IMGSIZE=500
    grayimg=cv.imread(os.path.join(PATH),cv.IMREAD_GRAYSCALE)
    resizedimg=cv.resize(grayimg,(IMG_SIZE,IMG_SIZE))
    croppedimg=resizedimg[250:470,100:370]
    gaborimg=[]
    gaborimg.append(gabor_filter(croppedimg,10,0,1*np.pi,4.2))
    gaborimg.append(gabor_filter(croppedimg,10,0,0,3.9))
    gaborimg.append(gabor_filter(croppedimg,10,0,1*np.pi,4.3))
    gaborimg.append(gabor_filter(croppedimg,10,30,1*np.pi,4.3))
    gaborimg.append(gabor_filter(croppedimg,10,30,1*np.pi,4.2))
    gaborimg.append(gabor_filter(croppedimg,10,25,0,3.9))
    medianimg=map(medianblurFunc,gaborimg)
    Guassimg=list(map(Gaussian_thresholding,medianimg))
#     L=[meanthinmg]
#     return np.array(L).reshape(-1,220,270,1)
    return np.array(Guassimg).reshape(-1,220,270,1)

In [95]:
new_model=tf.keras.models.load_model("Palmprint_detection_guass_optimzed.model")

In [96]:
np.argmax(new_model.predict(UploadImgGuass("test_img.jpg")))

1/1 [==============================] - 0s 113ms/step


10

In [97]:
list(map(np.argmax,new_model.predict(img)))

1/1 [==============================] - 0s 65ms/step


[10, 10, 10, 0, 7, 10]